[tool.poetry]
name = "standup"
version = "0.1.0"
description = "Agendaq for lrn support standup"
authors = ["Terry Brooks, Jr."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2.4"
loguru = "^0.7.0"
psycopg2-binary = "^2.9.7"
gunicorn = "^21.2.0"
django-crispy-forms = "^2.0"
whitenoise = "^6.5.0"
pendulum = "^2.1.2"
python-dotenv = "^1.0.0"
crispy-bootstrap5 = "^0.7"
django-htmx = "^1.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
